version: "3.7"
services:
  caddy:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - frontend
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
        frontend:
                internal: false
                external: false
                driver: bridge
        backend:
                internal: true
                external: false
                driver: bridge

volumes:
  caddy_data: {}
